site_name: Rahmet Pay API
nav:
- Главная: 'index.md'
- Авторизация: 'auth.md'
- Доступность оплаты: 'availability.md'
- Создание заказа: 'order.md'
- Проверка заказа перед оплатой: 'check_before_pay.md'
- Проверка статуса: 'status.md'
- Возврат: 'refund.md'
- Активный заказ: 'active_order.md'
theme: readthedocs
